const paragraphs = [
  "The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs.",
  "Technology shapes the way we live, work, and communicate every single day.",
  "Practice typing a little each day and speed will come naturally over time.",
  "Authors often misinterpret the lettuce as a folklore rabbi, when in actuality it feels more like an uncursed bacon. Pursued distances show us how mother-in-laws can be charleses.",
  "In modern times the first scrawny kitten is, in its own way, an input. An ostrich is the beginner of a roast. An appressed exhaust is a gun of the mind.",
  "Learning to type quickly and accurately is a skill that pays dividends throughout an entire career. Focus on rhythm rather than raw speed.",
  "The city never truly sleeps. Even at three in the morning, taxis splash through rain-slicked streets and bakeries begin preparing fresh bread.",
  "A well-written program solves a problem elegantly, using just enough code to be clear without being verbose or overly complicated.",
  "Mountains rise sharply from the valley floor, their snow-capped peaks touching the clouds on cold winter mornings after a heavy snowfall.",
  "Scientists have long debated the origins of consciousness, wondering whether it emerges purely from physical processes in the brain.",
  "There is no hunting like the hunting of man, and those who have hunted armed men long enough and liked it, never care for anything else thereafter.",
  "Time is too slow for those who wait, too swift for those who fear, too long for those who grieve, too short for those who rejoice, but for those who love, time is eternity.",
  "A man can be himself only so long as he is alone, and if he does not love solitude, he will not love freedom, for it is only when he is alone that he is really free.",
  "Whoever fights monsters should see to it that in the process he does not become a monster. And if you gaze long enough into an abyss, the abyss will gaze back into you.",
  "Do all the good you can, by all the means you can, in all the ways you can, in all the places you can, at all the times you can, to all the people you can, as long as ever you can.",
  "When one door closes, another opens, but we often look so long and so regretfully upon the closed door that we do not see the one which has opened for us.",
  "The cost of a thing is the amount of what I will call life which is required to be exchanged for it, immediately or in the long run.",
  "My moms always told me, 'How long you gonna play the victim?' I can say I'm mad and I hate everything, but nothing really changes until I change myself.",
  "To tell the truth, I'd rather be with you. I'd rather pick you up, I'd rather call the school. Don't matter where you are, don't matter what you do.",
  "Let's go find a place that's far from here, for real. Far from here. Nights like this, nights like this, I wish I could do the impossible.",
  "Maybe I'm the problem. No, I don't want drama. Do you really care? Or do you see a monster?",
  "If you have the opportunity to play this game of life you need to appreciate every moment. A lot of people don't appreciate the moment until it's passed.",
  "If you're you, it doesn't matter if you're the most boring person in the world: someone will like you. You're not trying to be anyone else.",
  "Everybody just has different steps in their life that they take to do what they should.",
  "If you believe in yourself, it will get you through it.",
  "Felt the love between us when we met. Don't be afraid, I guess I'll be right there. I need you to do just what I say. Knowin' it was destined, I could be your best friend.",
  "Some people only see the negative, some people find a way to see the good in everything.",
  "Some people want it all, but I don't want nothing at all. If it ain't you, baby, if I ain't got you, baby. Some people want diamond rings, some just want everything. But everything means nothing if I ain't got you.",
  "The cost of a thing is the amount of what I will call life which is required to be exchanged for it, immediately or in the long run.",
  "In the long run, the sharpest weapon of all is a kind and gentle spirit.",
  "The things we truly love stay with us always, locked in our hearts as long as life remains.",
  "In the sky there are always answers and explanations for everything: every pain, every suffering, joy and confusion.",
  "Deep into that darkness peering, long I stood there, wondering, fearing, doubting, dreaming dreams no mortal ever dared to dream before.",
  "Surround yourself with the best people you can find, delegate authority, and don't interfere as long as the policy you've decided upon is being carried out.",
  "No sound, once made, is ever truly lost. In electric clouds, all are safely trapped, and with a touch, if we find them, we can recapture those echoes of sad, forgotten wars, long summers, and sweet autumns.",
  "As long as you're being honest and there's intention in what you're doing, then I think that energy permeates your field and becomes like a homing signal for other people with like energies.",
  "It took me quite a long time to develop a voice, and now that I have it, I am not going to be silent.",
  "Death does not concern us, because as long as we exist, death is not here. And when it does come, we no longer exist.",
  "I learned a long time ago the wisest thing I can do is be on my own side, be an advocate for myself and others like me.",
  "What is ominous is the ease with which some people go from saying that they don't like something to saying that the government should forbid it. When you go down that road, don't expect freedom to survive very long.",
  "Millions long for immortality who don't know what to do with themselves on a rainy Sunday afternoon.",
  "Treasure the love you receive above all. It will survive long after your good health has vanished.",
  "Failure after long perseverance is much grander than never to have a striving good enough to be called a failure.",
  "A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.",
  "Look for yourself, and you will find in the long run only hatred, loneliness, despair, rage, ruin, and decay. But look for Christ, and you will find Him, and with Him everything else thrown in.",
  "There are risks and costs to action. But they are far less than the long range risks of comfortable inaction.",
  "Words are more powerful than some noises. Noises won't last long. Lyrics are so important, and people don't realise that.",
  "You must learn from the mistakes of others. You can't possibly live long enough to make them all yourself.",
  "The mind is the limit. As long as the mind can envision the fact that you can do something, you can do it, as long as you really believe 100 percent.",
  "Security is mostly a superstition. It does not exist in nature, nor do the children of men as a whole experience it. Avoiding danger is no safer in the long run than outright exposure. Life is either a daring adventure, or nothing.",
  "I think that helping people is a wonderful thing to be able to do. But, I can't really say that I like them. I don't believe their methods will reform the world or help others. In the end, I believe that is only something that you yourself can really solve.",
  "So long as you have food in your mouth, you have solved all questions for the time being.",
  "A team is where a boy can prove his courage on his own. A gang is where a coward goes to hide.",
  "Give me a lever long enough and a fulcrum on which to place it, and I shall move the world.",
  "If you live long enough, you'll make mistakes. But if you learn from them, you'll be a better person. It's how you handle adversity, not how it affects you. The main thing is never quit, never quit, never quit.",
  "It doesn't matter if a cat is black or white, so long as it catches mice.",
  "There are two things that won't last long in this world, and that's dogs chasing cars and pros putting for pars.",
];