const paragraphs = [
  "The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs.",
  "Technology shapes the way we live, work, and communicate every single day.",
  "Practice typing a little each day and speed will come naturally over time.",
  "Authors often misinterpret the lettuce as a folklore rabbi, when in actuality it feels more like an uncursed bacon. Pursued distances show us how mother-in-laws can be charleses.",
  "In modern times the first scrawny kitten is, in its own way, an input. An ostrich is the beginner of a roast. An appressed exhaust is a gun of the mind.",
  "Learning to type quickly and accurately is a skill that pays dividends throughout an entire career. Focus on rhythm rather than raw speed.",
  "The city never truly sleeps. Even at three in the morning, taxis splash through rain-slicked streets and bakeries begin preparing fresh bread.",
  "A well-written program solves a problem elegantly, using just enough code to be clear without being verbose or overly complicated.",
  "Mountains rise sharply from the valley floor, their snow-capped peaks touching the clouds on cold winter mornings after a heavy snowfall.",
  "Scientists have long debated the origins of consciousness, wondering whether it emerges purely from physical processes in the brain.",
  "There is no hunting like the hunting of man, and those who have hunted armed men long enough and liked it, never care for anything else thereafter.",
  "Time is too slow for those who wait, too swift for those who fear, too long for those who grieve, too short for those who rejoice, but for those who love, time is eternity.",
  "A man can be himself only so long as he is alone, and if he does not love solitude, he will not love freedom, for it is only when he is alone that he is really free.",
  "Whoever fights monsters should see to it that in the process he does not become a monster. And if you gaze long enough into an abyss, the abyss will gaze back into you.",
  "Do all the good you can, by all the means you can, in all the ways you can, in all the places you can, at all the times you can, to all the people you can, as long as ever you can.",
  "When one door closes, another opens, but we often look so long and so regretfully upon the closed door that we do not see the one which has opened for us.",
  "The cost of a thing is the amount of what I will call life which is required to be exchanged for it, immediately or in the long run.",
  "My moms always told me, 'How long you gonna play the victim?' I can say I'm mad and I hate everything, but nothing really changes until I change myself.",
  "To tell the truth, I'd rather be with you. I'd rather pick you up, I'd rather call the school. Don't matter where you are, don't matter what you do.",
  "Let's go find a place that's far from here, for real. Far from here. Nights like this, nights like this, I wish I could do the impossible.",
  "Maybe I'm the problem. No, I don't want drama. Do you really care? Or do you see a monster?",
  "If you have the opportunity to play this game of life you need to appreciate every moment. A lot of people don't appreciate the moment until it's passed.",
  "If you're you, it doesn't matter if you're the most boring person in the world: someone will like you. You're not trying to be anyone else.",
  "Everybody just has different steps in their life that they take to do what they should.",
  "If you believe in yourself, it will get you through it.",
  "Felt the love between us when we met. Don't be afraid, I guess I'll be right there. I need you to do just what I say. Knowin' it was destined, I could be your best friend.",
  "Some people only see the negative, some people find a way to see the good in everything.",
  "Some people want it all, but I don't want nothing at all. If it ain't you, baby, if I ain't got you, baby. Some people want diamond rings, some just want everything. But everything means nothing if I ain't got you.",
  "The cost of a thing is the amount of what I will call life which is required to be exchanged for it, immediately or in the long run.",
  "In the long run, the sharpest weapon of all is a kind and gentle spirit.",
  "The things we truly love stay with us always, locked in our hearts as long as life remains.",
  "In the sky there are always answers and explanations for everything: every pain, every suffering, joy and confusion.",
  "Deep into that darkness peering, long I stood there, wondering, fearing, doubting, dreaming dreams no mortal ever dared to dream before.",
  "Surround yourself with the best people you can find, delegate authority, and don't interfere as long as the policy you've decided upon is being carried out.",
  "No sound, once made, is ever truly lost. In electric clouds, all are safely trapped, and with a touch, if we find them, we can recapture those echoes of sad, forgotten wars, long summers, and sweet autumns.",
  "As long as you're being honest and there's intention in what you're doing, then I think that energy permeates your field and becomes like a homing signal for other people with like energies.",
  "It took me quite a long time to develop a voice, and now that I have it, I am not going to be silent.",
  "Death does not concern us, because as long as we exist, death is not here. And when it does come, we no longer exist.",
  "I learned a long time ago the wisest thing I can do is be on my own side, be an advocate for myself and others like me.",
  "What is ominous is the ease with which some people go from saying that they don't like something to saying that the government should forbid it. When you go down that road, don't expect freedom to survive very long.",
  "Millions long for immortality who don't know what to do with themselves on a rainy Sunday afternoon.",
  "Treasure the love you receive above all. It will survive long after your good health has vanished.",
  "Failure after long perseverance is much grander than never to have a striving good enough to be called a failure.",
  "A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.",
  "Look for yourself, and you will find in the long run only hatred, loneliness, despair, rage, ruin, and decay. But look for Christ, and you will find Him, and with Him everything else thrown in.",
  "There are risks and costs to action. But they are far less than the long range risks of comfortable inaction.",
  "Words are more powerful than some noises. Noises won't last long. Lyrics are so important, and people don't realise that.",
  "You must learn from the mistakes of others. You can't possibly live long enough to make them all yourself.",
  "The mind is the limit. As long as the mind can envision the fact that you can do something, you can do it, as long as you really believe 100 percent.",
  "Security is mostly a superstition. It does not exist in nature, nor do the children of men as a whole experience it. Avoiding danger is no safer in the long run than outright exposure. Life is either a daring adventure, or nothing.",
  "I think that helping people is a wonderful thing to be able to do. But, I can't really say that I like them. I don't believe their methods will reform the world or help others. In the end, I believe that is only something that you yourself can really solve.",
  "So long as you have food in your mouth, you have solved all questions for the time being.",
  "A team is where a boy can prove his courage on his own. A gang is where a coward goes to hide.",
  "Give me a lever long enough and a fulcrum on which to place it, and I shall move the world.",
  "If you live long enough, you'll make mistakes. But if you learn from them, you'll be a better person. It's how you handle adversity, not how it affects you. The main thing is never quit, never quit, never quit.",
  "It doesn't matter if a cat is black or white, so long as it catches mice.",
  "There are two things that won't last long in this world, and that's dogs chasing cars and pros putting for pars.",
  "Bureaucracy defends the status quo long past the time when the quo has lost its status.",
  "As long as the world is turning and spinning, we're gonna be dizzy and we're gonna make mistakes.",
  "Informed decision-making comes from a long tradition of guessing and then blaming others for inadequate results.",
  "As long as the people don't fear the truth, there is hope. For once they fear it, the one who tells it doesn't stand a chance. And today, truth is still beautiful... but so frightening.",
  "Everyone teases me in the family that I spend far too long chatting. So I think I've still got to learn a little bit more and to pick up a few more tips, I suppose.",
  "Life is often compared to a marathon, but I think it is more like being a sprinter; long stretches of hard work punctuated by brief moments in which we are given the opportunity to perform at our best.",
  "I have brought myself, by long meditation, to the conviction that a human being with a settled purpose must accomplish it, and that nothing can resist a will which will stake even existence upon its fulfillment.",
  "If you want to build a ship, don't drum up people to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea.",
  "You don't need to save the world to find meaning in life. Sometimes all you need is something simple, like someone to take care of.",
  "I don't know if I was a desirable person, not just physically but emotionally and mentally and intellectually. I still have a long way go and a lot to learn, but I'm on my way, I don't think I'm terribly attractive, but I'm comfortable with my looks.",
  "I think everybody longs to be loved and longs to know that he or she is lovable. And, consequently, the greatest thing that we can do is to help somebody know that they're loved and capable of loving.",
  "You don't get married because you've proven you're in love. You get married so that you can prove it.",
  "Some people ask the secret of our long marriage. We take time to go to a restaurant two times a week. A little candlelight, dinner, soft music and dancing. She goes Tuesdays, I go Fridays.",
  "If you want to build a ship, don't drum up people to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea.",
  "I'd wrap myself in the blanket at night against the cold and watch the bones take shape beneath my skin and I would pray that I might see the truth of the world before I died.",
  "The most important thing, in anything you do, is always trying your hardest, because even if you try your hardest and it's not as good as you'd hoped, you still have that sense of not letting yourself down.",
  "The strength of heart required to face oneself has been made manifest...",
  "I have learned that as long as I hold fast to my beliefs and values - and follow my own moral compass - then the only expectations I need to live up to are my own.",
  "Let us not seek the Republican answer or the Democratic answer, but the right answer. Let us not seek to fix the blame for the past. Let us accept our own responsibility for the future.",
  "Wisdom is not about knowing all the answers. It's about learning to live well with the questions, and finding peace in the space between what we know and what we'll never understand.",
  "The scars we carry are not signs of weakness; they are proof that we survived something that tried to break us, and in surviving, we became stronger than we knew we could be.",
  "Consistency beats intensity every single time. The small habits you repeat each day, the minor efforts you don't think twice about, these are the things that quietly reshape your entire life over months and years.",
  "The people who change the world are rarely the ones waiting for permission. They are the ones who saw a problem, believed they could help, and started before they felt ready.",
  "Regret doesn't come from the things you tried and failed at. It comes from the things you never attempted because you were too afraid of what others might think.",
  "The people worth keeping in your life are not the ones who make you feel perfect. They're the ones who see all your flaws and choose to stay, because they understand that imperfection is where real connection begins.",
  "The difference between dreamers and doers isn't talent or circumstance. It's the willingness to take the first step, even when the path ahead is unclear and there are no guarantees of success.",
  "What we resist tends to persist, but what we accept with curiosity begins to transform. The moment you stop fighting yourself is the moment you finally have the energy to build something worthwhile.",
  "You cannot hate yourself into becoming someone you love. Self-improvement built on shame and self-criticism will always crumble, but growth rooted in self-compassion endures.",
  "The people who matter most are usually the ones who stick around when you're at your worst, not your best. Remember them, because loyalty like that is rarer than you think.",
  "The strongest thing you can do is admit when you're struggling and ask for help. Vulnerability is not weakness; it's the only way to build real connection with other people.",
  "Comparison is the thief of joy because it measures your life against someone else's highlight reel. The moment you stop looking sideways at others and focus on your own journey is the moment you finally start making real progress.",
  "Not every chapter of your life will be a victory, and that's okay. Some chapters teach you, some humble you, and some simply remind you that you're still here, still trying, and that's enough for today.",
  "The future is not something that happens to you. It's something you build, one decision at a time, and every choice you make today is a brick in the foundation of who you'll become tomorrow.",
  "The most honest conversations often happen in silence, between two people who understand that sometimes being present is more powerful than having the perfect words to say.",
  "Your past doesn't define your future unless you use it as an excuse to stop trying. Every ending is just a blank page waiting for you to write something better than what came before.",
  "Growth doesn't happen in the comfortable moments. It happens when you push beyond what feels safe, when you're willing to be a beginner again, and when you accept that progress is messy before it becomes beautiful.",
  "The version of yourself you're trying to become is already inside you, waiting. You don't need to become someone else; you just need to stop pretending to be someone you're not.",
  "Forgiveness is not about excusing what someone did. It's about freeing yourself from the weight of carrying their mistakes around, so you have room to move forward with your own life.",
  "The people who inspire us most are not the ones who have it all figured out. They are the ones brave enough to show their struggles and honest enough to admit they're still learning, just like everyone else.",
  "The moments that matter most are usually the quiet ones, the unremarkable hours spent with people you love, doing nothing in particular, but everything that counts.",
  
];